# USB driver Makefile

USB_C := \
    usb.c \
    usb_keyboard.c \
    usb_mouse.c

# This Makefile is for building the USB drivers as part of the kernel
# The actual build rules are handled by the main kernel Makefile