/*
 * Notux OS — Path Compatibility Layer
 * kernel/fs/pathconv.h
 *
 * Translates POSIX-style paths to Notux internal paths.
 * This makes porting Linux/POSIX C programs easy — they can use
 * standard POSIX paths and they just work.
 *
 * Rules (applied in order):
 *   /                      → #/
 *   /home/alice/...        → #/usr/alice/...
 *   /home/...              → #/usr/...
 *   /tmp/...               → #/tmp/...
 *   /etc/...               → #/etc/...
 *   /bin/... /usr/bin/...  → #/bin/...
 *   /usr/local/bin/...     → #/bin/...
 *   /lib/... /usr/lib/...  → #/usr/lib/...
 *   /var/...               → #/var/...
 *   /proc/...              → #/sys/proc/...
 *   /dev/...               → #/dev/...
 *   /mnt/...               → #/mnt/...
 *   /opt/...               → #/usr/opt/...
 *   /root/...              → #/usr/admin/...
 *   Any other /...         → #/...
 *   #/... (already Notux)  → unchanged
 *   Relative paths         → unchanged
 */
#pragma once
#include <stddef.h>

/*
 * Translate a path into Notux format.
 * dst must be at least VFS_PATH_MAX bytes.
 * Returns dst.
 */
char *path_to_notux(const char *src, char *dst, size_t dst_size);

/*
 * Translate a Notux path back to POSIX for apps that need it.
 * Returns dst.
 */
char *path_to_posix(const char *src, char *dst, size_t dst_size);
